version: '3'
services:

  mq:
    image: "ibmcom/mq"
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
    ports:
      - "1414:1414"
      - "9443:9443"

  spring-boot-admin-server:
    image: "spring-boot-admin-server:1.0-SNAPSHOT"
    ports:
      - 8080:8080
    environment:
      STARTUP_WAIT_TIME: 0
      spring_profiles_active: local

  dummy-responder:
    image: "dummy-responder:1.0-SNAPSHOT"
    ports:
      - 8082:8082
    environment:
      STARTUP_WAIT_TIME: 10
      spring_profiles_active: local
      spring.boot.admin.client.url: "http://spring-boot-admin-server:8080"
      ibm.mq.connName: "mq(1414)"
      ibm.mq.queueManager: "QM1"

  atm-server:
    image: "atm-server:1.0-SNAPSHOT"
    ports:
      - 8081:8081
      - 8992:8992
    environment:
      STARTUP_WAIT_TIME: 20
      spring_profiles_active: local
      spring.boot.admin.client.url: "http://spring-boot-admin-server:8080"
      qm.list.0.connName: "mq(1414)"
      qm.list.0.queueManager: "QM1"
      ibm.mq.connName: "mq(1414)"
      ibm.mq.queueManager: "QM1"
      atm.server.registry-location: "/etc/atm-server/registry.txt"
      atm.server.routing-location: "/etc/atm-server/routing.txt"
    volumes:
      - ./upload-registry/registry.txt:/etc/atm-server/registry.txt:ro
      - ./atm-server/routingTable.txt:/etc/atm-server/routing.txt:ro

  atm-client-web:
    image: "atm-client-web:1.0-SNAPSHOT"
    ports:
      - 8085:8085
    environment:
      STARTUP_WAIT_TIME: 30
      spring_profiles_active: local
      spring.boot.admin.client.url: "http://spring-boot-admin-server:8080"
      iso-server-host: atm-server
      iso-server-port: 8992
