version: '3'
services:

  mq:
    image: "ibmcom/mq"
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
    ports:
      - "1414:1414"
      - "9443:9443"

  admin:
    image: "admin:1.0-SNAPSHOT"
    ports:
      - 8080:8080
    environment:
      STARTUP_WAIT_TIME: 0
      spring_profiles_active: local

  dummy-responder:
    image: "dummy-responder:1.0-SNAPSHOT"
    ports:
      - 8082:8082
    environment:
      STARTUP_WAIT_TIME: 20
      spring_profiles_active: local
      spring.boot.admin.client.url: "http://admin:8080"
      ibm.mq.connName: "mq(1414)"

  atm-server:
    image: "atm-server:1.0-SNAPSHOT"
    ports:
      - 8081:8081
      - 8992:8992
    environment:
      STARTUP_WAIT_TIME: 40
      spring_profiles_active: local
      spring.boot.admin.client.url: "http://admin:8080"
      ibm.mq.connName: "mq(1414)"
      atm.server.registry-location: "/etc/registry.txt"
    volumes:
      - ./upload-registry/registry.txt:/etc/registry.txt:ro
