apiVersion: v1
kind: ConfigMap
metadata:
  name: atm-server-configmap
data:
  application.properties: |-
    spring.boot.admin.client.url=http://spring-boot-admin-server:8080
    spring.zipkin.baseUrl=http://zipkin.istio-system:9411
    spring.zipkin.enabled=true
    qm.list.0.channel=${MQ_0_CHANNEL}
    qm.list.0.connName=${MQ_0_HOST}(${MQ_0_PORT})
    qm.list.0.password=${MQ_0_PASSWORD}
    qm.list.0.queueManager=${MQ_0_QM}
    qm.list.0.user=${MQ_0_USER}
    ibm.mq.channel=${MQ_CHANNEL}
    ibm.mq.connName=${MQ_HOST}(${MQ_PORT})
    ibm.mq.password=${MQ_PASSWORD}
    ibm.mq.queueManager=${MQ_QM}
    ibm.mq.user=${MQ_USER}
    atm.server.socket-port=8992
    atm.server.registry-location=/etc/atm-server/registry.txt
    atm.server.routing-location=/etc/atm-server/routing.txt
  registry: |-
    000000001111
    000000002222
    000000003333
    000000004444
  routing: |-
    #ATM_ID	MSG_ID	DEST
    .*01$	9380	DEV.QUEUE.3 QM1
    .*01$	7200	DEV.QUEUE.2 QM1
    .*01$	*	DEV.QUEUE.9 QM1
    .*2$	*	DEV.QUEUE.9 QM1
    .*1$	*	DEV.QUEUE.1 QM1
    .*3$	*	DEV.QUEUE.1 QM1
    .*4$	*	DEV.QUEUE.1 QM1
    *	9380	DEV.QUEUE.3 QM1
    *	*	DEV.QUEUE.1 QM1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: atm-server-deployment
spec:
  selector:
    matchLabels:
      app: atm-server
  replicas: 1
  template:
    metadata:
      labels:
        app: atm-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/actuator/prometheus"
        kiali.io/runtimes: springboot-jvm,springboot-jvm-pool,springboot-tomcat
    spec:
      containers:
        - name: atm-server
          image: "atm-server:1.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
            - containerPort: 8992
              name: netty
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: minikube
            - name: MQ_USER
              valueFrom:
                secretKeyRef:
                  name: mq-secret
                  key: mq-user
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mq-secret
                  key: mq-password
            - name: MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: mq-configmap
                  key: mq-host
            - name: MQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: mq-configmap
                  key: mq-port
            - name: MQ_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: mq-configmap
                  key: mq-channel
            - name: MQ_QM
              valueFrom:
                configMapKeyRef:
                  name: mq-configmap
                  key: mq-qm
            - name: MQ_0_USER
              valueFrom:
                secretKeyRef:
                  name: mq-secret
                  key: mq-0-user
            - name: MQ_0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mq-secret
                  key: mq-0-password
            - name: MQ_0_HOST
              valueFrom:
                configMapKeyRef:
                  name: mq-configmap
                  key: mq-0-host
            - name: MQ_0_PORT
              valueFrom:
                configMapKeyRef:
                  name: mq-configmap
                  key: mq-0-port
            - name: MQ_0_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: mq-configmap
                  key: mq-0-channel
            - name: MQ_0_QM
              valueFrom:
                configMapKeyRef:
                  name: mq-configmap
                  key: mq-0-qm
          volumeMounts:
            - name: atm-server-volume
              mountPath: /etc/atm-server
      volumes:
        - name: atm-server-volume
          configMap:
            name: atm-server-configmap
            items:
              - key: registry
                path: registry.txt
              - key: routing
                path: routing.txt

---

apiVersion: v1
kind: Service
metadata:
  name: atm-server
  labels:
    app: atm-server
    spring-boot: "true"
spec:
  selector:
    app: atm-server
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
    - protocol: TCP
      name: netty
      port: 8992
      targetPort: 8992
      nodePort: 30992

---
