apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-deployment
spec:
  selector:
    matchLabels:
      app: mq
  replicas: 1
  template:
    metadata:
      labels:
        app: mq
    spec:
      containers:
        - name: mq
          image: "ibmcom/mq"
          ports:
            - containerPort: 1414
            - containerPort: 9443
          env:
            - name: LICENSE
              value: accept
            - name: MQ_QMGR_NAME
              value: QM1

---

apiVersion: v1
kind: Service
metadata:
  name: mq
spec:
  selector:
    app: mq
  type: NodePort
  ports:
    - name: listener
      protocol: TCP
      port: 1414
      targetPort: 1414
      nodePort: 32014
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 32043

---
